[package]
name = "rust-player"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.8"
crossterm = "0.27.0"
futures = "0.3.30"
glob = "0.3.1"
soloud = "1.0.5"
tokio = "1.38.0"
tui = "0.19.0"
